force-app/main/default/objects/Portfolio__c/Portfolio__c.object-meta.xml
<CustomObject>
    <label>Portfolio</label>
    <nameField>
        <label>Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portfolios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portfolio__c/fields/AboutMe__c.field-meta.xml
<CustomField>
    <fullName>AboutMe__c</fullName>
    <label>AboutMe</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/CertificationData__c.field-meta.xml
<CustomField>
    <fullName>CertificationData__c</fullName>
    <label>CertificationData</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/LinkedInProfile__c.field-meta.xml
<CustomField>
    <fullName>LinkedInProfile__c</fullName>
    <label>LinkedInProfile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/ResumeURL__c.field-meta.xml
<CustomField>
    <fullName>ResumeURL__c</fullName>
    <label>ResumeURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/SalesforceStackoverflowProfile__c.field-meta.xml
<CustomField>
    <fullName>SalesforceStackoverflowProfile__c</fullName>
    <label>SalesforceStackoverflowProfile</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/StackoverflowData__c.field-meta.xml
<CustomField>
    <fullName>StackoverflowData__c</fullName>
    <label>StackoverflowData</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/TrailheadProfileURL__c.field-meta.xml
<CustomField>
    <fullName>TrailheadProfileURL__c</fullName>
    <label>TrailheadProfileURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portfolio__c/fields/WhatIAm__c.field-meta.xml
<CustomField>
    <fullName>WhatIAm__c</fullName>
    <label>WhatIAm</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Technical Architect</fullName>
            </value>
            <value>
                <fullName>Passionate Coder</fullName>
            </value>
            <value>
                <fullName>Web Developer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PortfolioExperience__c/PortfolioExperience__c.object-meta.xml
<CustomObject>
    <label>PortfolioExperience</label>
    <nameField>
        <label>PortfolioExperience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PortfolioExperiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PortfolioExperience__c/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <label>CompanyName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortfolioExperience__c/fields/JobDescription__c.field-meta.xml
<CustomField>
    <fullName>JobDescription__c</fullName>
    <label>JobDescription</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PortfolioExperience__c/fields/JobDuration__c.field-meta.xml
<CustomField>
    <fullName>JobDuration__c</fullName>
    <label>JobDuration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortfolioExperience__c/fields/JoiningYear__c.field-meta.xml
<CustomField>
    <fullName>JoiningYear__c</fullName>
    <label>JoiningYear</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PortfolioExperience__c/fields/Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portfolio</label>
    <referenceTo>Portfolio__c</referenceTo>
    <relationshipLabel>PortfolioExperiences</relationshipLabel>
    <relationshipName>PortfolioExperiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PortfolioController.cls
/**
 * Created by nagendrakumar.singh on 16/04/23.
 */

public without sharing class PortfolioController {

    @AuraEnabled(Cacheable=true)
    public static Portfolio__c fetchPortfolioData() {
        return [
                SELECT
                        AboutMe__c,
                        CertificationData__c,
                        PhoneNumber__c,
                        LinkedInProfile__c,
                        Name,
                        SalesforceStackoverflowProfile__c,
                        StackoverflowData__c,
                        TrailheadProfileURL__c,
                        WhatIAm__c,ResumeURL__c, (
                        SELECT
                                CompanyName__c,
                                JobDescription__c,
                                JobDuration__c,
                                JoiningYear__c,
                                Name,
                                Portfolio__c
                        FROM PortfolioExperiences__r ORDER BY JoiningYear__c
                )
                FROM Portfolio__c
        ];
    }

}